jobs:
  publish:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      env:
        ossrhPassword: ${{ secrets.OSSRHUSERNAME }}
        ossrhUsername: ${{ secrets.OSSRHPASSWORD }}
      name: Build with Gradle
      uses: gradle/gradle-build-action@v2.6.0
      with:
        arguments: publish
name: Gradle publish Snapshot
on:
  repository_dispatch:
    types: trigger-ga___gradle_publish.yml
permissions:
  contents: read
