jobs:
  deploy:
    name: Java ${{ matrix.java }} building ...
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java }}
        server-id: sonatype-nexus-snapshots
        server-password: MAVEN_PASSWORD
        server-username: MAVEN_USERNAME
    - continue-on-error: true
      env:
        MAVEN_PASSWORD: ${{ secrets.OSSRHPASSWORD }}
        MAVEN_USERNAME: ${{ secrets.OSSRHUSERNAME }}
      name: Build with Maven
      run: mvn -B deploy --file pom.xml -DdisableXmlReport=true -Djacoco.skip=true
        -Dpmd.skip=true
    strategy:
      matrix:
        java:
        - 11
name: Maven deploy snapshot
on:
  repository_dispatch:
    types: trigger-ga___maven_deploy.yml
